### ISSUE TITLE
[ComfyU] Update Failures

### ISSUE THREAD

**Issue by WeirdScienceX** [AIrjen/OneButtonPrompt#168]
Recently, updates always fail for One Button Prompt.  Removing and reinstalling does not rectify the issue

> Update custom node 'One Button Prompt'
> Update: ['https://github.com/AIrjen/OneButtonPrompt']
> Cmd('git') failed due to: exit code(1)
>  cmdline: git pull -v -- origin
>  stderr: 'error: The following untracked working tree files would be overwritten by merge:'
> CUSTOM NODE PULL: Fail

**Comment by gordingus** [comment]
Same here

**Comment by AIrjen** [comment]
Hi, I think I got it solved in latest version. I can't fully reproduce here (since I am already on latest version).

A full reinstall should work now. I had a conflict with a the presets file that is created on local system only, but somehow snuck into the solution.

If a full reinstall doesnt work, go into the OneButtonPrompt\userfiles folder and move out (or remove) the obp_presets.json file. The file will be recreated on first use.

Hope this helps, let me know if it worked.

**Comment by WeirdScienceX** [comment]
I can confirm that has resolved the issue, thanks for the quick response!

**Comment by AIrjen** [comment]
Thanks for confirming! :)
