### ISSUE TITLE
[Feature Request] Option to lock in the seed

### ISSUE THREAD

**Issue by Zotikus1001** [AIrjen/OneButtonPrompt#203]
Add an option to use the same generation seed, so that OBP prompt improvements give the same exact result when using the same seed.

**Comment by AIrjen** [comment]
Hi! Seeds are already part of the ComfyUI nodes, it just hasn't been brought to the A1111 interface.

Will put this on the dev list, will give an update when its done.

**Comment by AIrjen** [comment]
Hi Zotikus,

I think I don't understand your request correctly. I thought you were talking about addings seeds to the A1111 interface, but that doesn't seem to be the case.

The more I think about that, the harder it gets. You don't want to link the seed up with the image seed since it would get the same image with the same prompt each time.

Having it somewhere else in the interface in A1111 is clunky, and then the workflow tab becomes the better solution, to run images with the same prompt.

So I guess what you ARE asking, is that the results of the seed in ComfyUI stay the same for each release of One Button Prompt. This is not going to be possible, it is not build to do that at all.
