### ISSUE TITLE
Batch size

### ISSUE THREAD

**Issue by soulsleuth** [AIrjen/OneButtonPrompt#24]
After setting the batch size and using this script, images will not be generated in batches according to the batch size, but rather generated one after another.

**Comment by AIrjen** [comment]
Hi! Thanks for reporting this. I've noticed the same behavior as well, but haven't been to able to find a solution yet.
I'll try and restart the investigation, to see if I pinpoint the exact problem.

**Comment by AIrjen** [comment]
Hi! I had to finish the autorun branch first. Since I did that today, I finally had time to research the problem. 
I got a fix in, it now works as expected :)

![image](https://github.com/AIrjen/OneButtonPrompt/assets/130234949/a8c401b8-042f-447e-b290-046644fa51c7)

**Comment by tusharbhutt** [comment]
Does this mean if I have a batch size of three that I should get three random prompts like Dynamic Prompts?  That would be cool, but based on the image above, it does not appear so

**Comment by AIrjen** [comment]
Hi, Here is an update. I got really stuck trying to get a different prompt for each Batch size.
I've done some research into how X/Y/Z plot and Dynamic Prompts extentension are handling this. Turns out, they don't have this behavior either.
Meaning, One Button Prompt behaves exactly the same.
Setting a Batch count -> different result each Batch count
Setting a Batch size -> same prompt used for each batch size

**Comment by AIrjen** [comment]
Here is another update: 
The "Unprompted" extension was causing my installation to behave differently.
This is back on the todo list, and will be picked up after the next big update (1-2 weeks)

**Comment by Jonseed** [comment]
@AIrjen I would also like to be able to generate images in batch sizes greater than 1, but I don't want them to all be the very same prompt in the batch. With Dynamic Prompts, I _**do**_ get a different prompt for each image in a single batch, so somehow it seems possible. Can you look into this again?

**Comment by AIrjen** [comment]
Hi! I have spend multiple sessions on this trying to get this to work. I have figured out why it is not (currently) possible with One Button Prompt.

There are 2 types of extension in A1111. Active (like Dynamic Prompts) and scripts.
The script extensions are executed before/or are part of processing the images.

The active scripts are activated during processing.

To make One Button Prompt work like this would mean to rewrite it as an active extension. It would then probably start to conflict with other extensions, instead of working together with them.

I am not totally against this idea, but it means a considerable rewrite/rethink. If I do, it would be like a 2.0 version. It is not currently on the short term planning to do so.
