### ISSUE TITLE
Windows Paths wrong

### ISSUE THREAD

**Issue by JoBilert** [AIrjen/OneButtonPrompt#31]
When I run the script, it seems to process all paths in a wrong manner.

e.g. Instead of E:\ImageAI\models\protogenX53OfficialR_10.safetensor it only looks for E:ImageAImodelsprotogenX53OfficialR_10

Same with VAEs and Upscalers

**Comment by AIrjen** [comment]
Hi, thanks for reporting this. I will research this over the weekend.

I'm actually using some code from inside WebUI for this, so I need to check why it isn't working for you. Might take some time to rebuild/research and solve.

**Comment by JoBilert** [comment]
> Hi, thanks for reporting this. I will research this over the weekend.
> 
> I'm actually using some code from inside WebUI for this, so I need to check why it isn't working for you. Might take some time to rebuild/research and solve.

Thanks a  lot.

**Comment by AIrjen** [comment]
Hi, I just pushed a fix with a potential fix.
I redid the way models are loaded, which is more in line with how WebUI does it nativly. I think I used an outdated component of WebUI earlier.

I also found out some other issues while investigating this, the random model option didn't work. So that was fixed as well.

Let me know if this fix works, you can install the latest version.

To be safe, restart WebUI completely after installing.

**Comment by AIrjen** [comment]
Closing this, had no more reports about this issue after fix was implemented.
