### ISSUE TITLE
FileNottFound Error Images not saving 

### ISSUE THREAD

**Issue by RanjithKannan03** [AIrjen/OneButtonPrompt#77]
[Errno 2] No such file or directory: 'C:\Users\rkran\AI-StableDiffusion\stable-diffusion-webui\extensions\OneButtonPrompt\./automated_outputs/txt2img/20230708021655_enshogun\_(genshin_impact\)__0.png'. Whenever an image finishes generating i get an error like this. What should i do?

**Comment by AIrjen** [comment]
Well, what you should do, is create an issue with the description of the error message. Which you did!

It seems somehow on your computer (assuming its not a standard windows machine?) the folders it's trying to create isn't attaching properly. There is a little dot after OneButtonPrompt. I can't reproduce this locally.

So what I did, is change the code, and check after generating the directory, wether there is a ./ in there, and then change it to /

This should fix your issue! Please let me know if it works for you after you get the latest version.

**Comment by sdUserzz** [comment]
It looks like this issue is happening when the script tries to incorporate an F-stop setting from the prompt into the file name.  I get this error any time the file being created has the following string in it:  _F/_.
As a workaround I initially tried entering "F/*" into the Filter Out field, but that didn't work as I guess wildcards don't work there.
I ended up creating a 'antilist,csv' file listing all the possible F-stops between F/1 and F/32 including 1/3 stops (it ended up being 40 values.  That seems to have done the trick.  I don't ever get the FileNotFound error now, but of course I don't get F-stops in my prompts any more. :)
If anyone else is having this issue give this a shot till it's fixed.

**Comment by AIrjen** [comment]
Hi! First of all, thank you so much for reporting this.

It's the joys of programming, changing something at location A, and it now breaks at location B.

Issue has been resolved, made a quick fix for latest version.

Again, thank you!
