### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by some9000** [AIrjen/OneButtonPrompt#9]
Hi! You haven't enabled discussions so I'll just write here.

First of all, thanks for the shoutout in your description. I have been planning on improving the lousy version that was in StylePile. For now the solution was to just ask an AI to generate a ton of interesting prompts, split them apart and then to either load them complete or merge like StylePile did up to now. But that still is a little clumsy so, for now, I decided to focus on doing something like that by hand using variables and such (can check it out at https://github.com/some9000/StylePile/tree/Beta-2.1 if you'd like).

It is interesting to see that we have both come up to certain ideas (like the way batch generation separates the prompts). But yours is, certainly a much more specialized product and it excels at that.

**Comment by AIrjen** [comment]
Hi! I love StylePile. It's my favorite extension and I think it isn't discussed/used enough. Love to see you are still working on it.

I started out this project as an autogenerator for windows wallpapers/google meet backgrounds for personal use. First idea was to get data from news headlines of the day, but as it turns out. Its mostly bad news. A lot of the initial idea is inspired on stylepile, and you can find some of your ideas still in there. Slowly it grew into something bigger, and then I converted it to a extension for automatic1111. The old code is still there, so it has an automatic process to generate images and upscale them as well. 

I will definitely take a look at your github and contact you later. Don't hesitate to take some code, ideas or some of the lists as well.
